# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 06:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('year_published', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
                ('genre', models.IntegerField(choices=[(0, 'Science fiction'), (1, 'Drama'), (2, 'Action and Adventure'), (3, 'Romance'), (4, 'Mystery'), (5, 'Health'), (6, "Children's"), (7, 'Science'), (8, 'History'), (9, 'Biographies')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BookForSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('sold', models.BooleanField(default=False)),
                ('condition', models.IntegerField(choices=[(0, 'Poor'), (1, 'Fair'), (2, 'Good'), (3, 'New')], max_length=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookSell.Book')),
                ('userBought', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bought', to=settings.AUTH_USER_MODEL)),
                ('userSelling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_selling', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ourUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ourUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sellBookForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('year_published', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('genre', models.IntegerField(choices=[(0, 'Science fiction'), (1, 'Drama'), (2, 'Action and Adventure'), (3, 'Romance'), (4, 'Mystery'), (5, 'Health'), (6, "Children's"), (7, 'Science'), (8, 'History'), (9, 'Biographies')])),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
