# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookSell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookForSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phoneNumber', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='description', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='year_published',
            field=models.IntegerField(default=2001),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookforsale',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookSell.Book'),
        ),
        migrations.AddField(
            model_name='bookforsale',
            name='userBought',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bought', to='bookSell.User'),
        ),
        migrations.AddField(
            model_name='bookforsale',
            name='userSelling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_selling', to='bookSell.User'),
        ),
    ]
