# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookSell', '0002_auto_20161009_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='author', max_length=200),
            preserve_default=False,
        ),
    ]
