# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookSell', '0004_auto_20161009_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookforsale',
            name='userBought',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_bought', to='bookSell.User'),
            preserve_default=False,
        ),
    ]
